version: '3.7'
services:
    node-app:
        build: ./artifacts/gate-simulator
        image: node-app:1.0
        container_name: node
        ports:
            - '9999:9999'
    mysql:
        image: mysql:latest
        container_name: mysql-container
        command: --innodb_use_native_aio=0
        ports:
            - '3306:3306'
        volumes:
            - ./data:/var/lib/mysql
            #- ./artifacts/init_db:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=app
            - MYSQL_USER=app
            - MYSQL_PASSWORD=pass
    postgres:
        image: postgres:12-alpine
        container_name: postgres
        ports:
            - '5432:5432'
        volumes:
            - ./pgdata:/var/lib/postgresql/pgdata
        environment:
            - POSTGRES_PASSWORD=pass
            - POSTGRES_USER=app
            #- PGDATA=/var/lib/postgresql/pgdata
            - POSTGRES_DB=app
